### <font color="brown">NumPy - Continued</font>

In [4]:
import numpy as np

---

#### <font color="brown">Type Casting</font>

##### You can CAST an array from one dtype to another using astype method.<br>Using astype ALWAYS CREATES A NEW ARRAY, leaving the original array untouched

In [2]:
floatarr = np.array([1,2.5,3])
floatarr.dtype

dtype('float64')

In [4]:
intarr = floatarr.astype(np.int64)
intarr, intarr.dtype

(array([1, 2, 3], dtype=int64), dtype('int64'))

In [5]:
# or, can just say int instead of np.int64
intarr2 = floatarr.astype(int)
intarr2, intarr2.dtype

(array([1, 2, 3]), dtype('int32'))

In [6]:
num_strings = np.array(['1.5', '3.6', '-2.9'])
narr = num_strings.astype(float)  
narr, narr.dtype

(array([ 1.5,  3.6, -2.9]), dtype('float64'))

In [8]:
# x.y is not the float *error*
np.array(['1.2','2.5','x.y']).astype(float)

ValueError: could not convert string to float: 'x.y'

In [9]:
# assign another array's dtype to intarr
farr = intarr.astype(floatarr.dtype) 
farr, intarr

(array([1., 2., 3.]), array([1, 2, 3], dtype=int64))

---

#### <font color="brown">Array-array and array-scalar operations</font>

##### Batch operations applied to arrays as a whole is called <em>vectorization</em>

In [5]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
arr * arr * arr

array([[  1,   8,  27],
       [ 64, 125, 216]])

In [7]:
arr + arr  

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [8]:
1/arr  

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [9]:
arr ** 2  

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

In [10]:
np.power(arr,2)

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

In [15]:
np.power(arr,3).astype(np.int64)

array([[  1,   8,  27],
       [ 64, 125, 216]], dtype=int64)

---

#### <font color="brown">Indexing and Slicing</font>

#### 1D Array

In [17]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
arr[5:8]

array([5, 6, 7])

In [19]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [20]:
arr[:-2]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [21]:
arr[-3:]

array([7, 8, 9])

In [22]:
arr[3:-5]

array([3, 4])

**What happens when you modify a slice?**

In [23]:
arr_slice = arr[5:8]
arr_slice

array([5, 6, 7])

In [24]:
arr_slice[1] = 66  
arr  # what happens to the original?

array([ 0,  1,  2,  3,  4,  5, 66,  7,  8,  9])

In [28]:
arr[5:8][1] = 7    # wihtout using slice on the orignial array
arr

array([0, 1, 2, 3, 4, 5, 7, 7, 8, 9])

In [29]:
arr[5:8] = 10  # modify original
arr

array([ 0,  1,  2,  3,  4, 10, 10, 10,  8,  9])

In [33]:
arr_slice[:] = 13 
arr

array([ 0,  1,  2,  3,  4, 13, 13, 13,  8,  9])

In [37]:
# make an explcicit copy of a slice
slice_copy = arr[5:8].copy()
print(slice_copy)

slice_copy[1] = 66
print(slice_copy[1])

print(arr)
print(slice_copy)

[13 13 13]
66
[ 0  1  2  3  4 13 13 13  8  9]
[13 66 13]


---

#### 2D Array

In [42]:
myarr = np.arange(1,10).reshape(3,3)
myarr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
myarr[1]      # 1st element of horizantial way (Row)

array([4, 5, 6])

In [44]:
myarr[:,2]     # 3rd element of vertical way (Col)

array([3, 6, 9])

In [45]:
myarr[:,1]     # 1st element of vertical way (Col)

array([2, 5, 8])

In [46]:
myarr[:,0]     # 2nd element of vertical way (Col)

array([1, 4, 7])

In [47]:
myarr[[0,2]]  # this not 0 to 2, just 1st and 3rd element

array([[1, 2, 3],
       [7, 8, 9]])

In [49]:
myarr[[-3,-2]]

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
myarr[[0,2]]

array([[1, 2, 3],
       [7, 8, 9]])

In [71]:
myarr[:,[0,2]]

array([[1, 3],
       [4, 6],
       [7, 9]])

In [72]:
myarr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [74]:
myarr[[2,0,1]]          #replace [frist, second, last row]

array([[7, 8, 9],
       [1, 2, 3],
       [4, 5, 6]])

In [75]:
myarr[:,[2,0,1]]

array([[3, 1, 2],
       [6, 4, 5],
       [9, 7, 8]])

In [76]:
myarr[1] = [-1,-2,-3]    # replace the 2nd row
myarr

array([[ 1,  2,  3],
       [-1, -2, -3],
       [ 7,  8,  9]])

In [78]:
myarr[:,2] = [2,1,0]     # replace the 3rd Col
myarr

array([[ 1,  2,  2],
       [-1, -2,  1],
       [ 7,  8,  0]])

In [79]:
myarr[:,2] = -1    # replace the 3rd Col to -1

myarr

array([[ 1,  2, -1],
       [-1, -2, -1],
       [ 7,  8, -1]])

**Row and column index lists**

In [59]:
narr = np.arange(32).reshape(8,4)
narr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [60]:
narr[[2,4,0,7],[1,2,0,3]]  

array([ 9, 18,  0, 31])

In [62]:
narr[[2,4,0,7]]  
print(narr)
print(type(narr))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
<class 'numpy.ndarray'>


In [84]:
narr[[2,4,0,7]][:,[1,2,3,0]] 

array([[ 9, 10, 11,  8],
       [17, 18, 19, 16],
       [ 1,  2,  3,  0],
       [29, 30, 31, 28]])

In [85]:
# what does this do?
narr_subrows = narr[[2,4,0,7]]
print(narr_subrows,'\n')
narr_subrows_shuffle = narr_subrows[:,[1,2,3,0]]
print(narr_subrows_shuffle)

[[ 8  9 10 11]
 [16 17 18 19]
 [ 0  1  2  3]
 [28 29 30 31]] 

[[ 9 10 11  8]
 [17 18 19 16]
 [ 1  2  3  0]
 [29 30 31 28]]


**Modifying row slice**

In [86]:
arr2d = np.arange(1,10).reshape(3,3)
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [87]:
rowslc = arr2d[1:]       # include arrange 1 to end
rowslc

array([[4, 5, 6],
       [7, 8, 9]])

In [91]:
rowslc[0] = [10, 1, 2]  # modify the slice when type just 10 all element at 0 will be change to 10
rowslc

array([[10,  1,  2],
       [ 7,  8,  9]])

In [93]:
rowslc[0] = 10  # modify the slice 
rowslc

array([[10, 10, 10],
       [ 7,  8,  9]])

In [94]:
arr2d  # is original array modified?

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

**Modifying column slice**

In [63]:
arr2d = np.arange(1,10).reshape(3,3)
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
colslc = arr2d[[0,2]]  
colslc

array([[1, 2, 3],
       [7, 8, 9]])

In [73]:
colslc = arr2d[:, [0,2]]  
colslc

array([[1, 3],
       [4, 6],
       [7, 9]])

In [77]:
colslc[:,1] = 10  # modify the slice
print(colslc)
print(type(colslc))

[[ 1 10]
 [ 4 10]
 [ 7 10]]
<class 'numpy.ndarray'>


In [98]:
arr2d # is original array modified?

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

---

#### <font color="brown">Slicing using a boolean filter (mask)</font>

In [78]:
arr=np.arange(9)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [79]:
slc = arr[arr > 4]  # pick elements > 4
slc

array([5, 6, 7, 8])

In [80]:
filter = arr > 4
filter

array([False, False, False, False, False,  True,  True,  True,  True])

In [81]:
slc = arr[filter]
slc

array([5, 6, 7, 8])

In [82]:
slc[0] = 10
slc

array([10,  6,  7,  8])

In [83]:
arr  # is original array modified?

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [84]:
arr2d = np.arange(1,13).reshape(4,3)
arr2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [86]:
arr2d_slc = arr2d[[True,False,True,True]]   # base on Row
print(arr2d_slc)

[[ 1  2  3]
 [ 7  8  9]
 [10 11 12]]


In [87]:
arr2d_slc[0] = 0  # modify 1st row of slice
arr2d_slc

array([[ 0,  0,  0],
       [ 7,  8,  9],
       [10, 11, 12]])

In [88]:
arr2d  # is original modified?

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [95]:
arr2d[[i%2 == 0 for i in range(4)]]  

array([[1, 2, 3],
       [7, 8, 9]])

**Applying a boolean mask from one array to another**

In [97]:
numarr = np.array([2,5,4,12])
numarr 

array([ 2,  5,  4, 12])

In [99]:
numarr = np.array([2,5,4,12])
arr2d[(numarr % 2 == 0)]   

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [10, 11, 12]])

In [100]:
arr2d[~(numarr % 2 == 0)]  

array([[4, 5, 6]])

In [101]:
arr2d[(numarr % 2 == 0),0]  

array([ 1,  7, 10])

In [102]:
mask = (numarr < 3) | (numarr > 10)
mask

array([ True, False, False,  True])

In [103]:
arr2d[mask] 

array([[ 1,  2,  3],
       [10, 11, 12]])

In [104]:
arr2dcopy = arr2d.copy()
arr2dcopy[arr2dcopy > 9] = 0  # set all values > 9 to 0
arr2dcopy

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [0, 0, 0]])

In [108]:
arr2dcopy = arr2d.copy()
arr2dcopy[(arr2dcopy < 2) | (arr2dcopy > 6)] = -1  
arr2dcopy

array([[-1,  2,  3],
       [ 4,  5,  6],
       [-1, -1, -1],
       [-1, -1, -1]])

**Global filtering with any and all**

In [109]:
arr = np.array([0,1,-5,2,9,0,3,-4,6])
print(arr.any())   

True


In [119]:
np.zeros(9).any()

False

In [120]:
arr.all()

False

In [121]:
np.ones(9).all()

True

---

#### Universal Function, or ufunc, is a function that performs element-wise operations on ndarrays.<br>Unary ufuncs work on a single ndarry, binary ufuncs work on a pair

---

#### <font color="brown">Some unary ufuncs</font>

In [110]:
arr = np.arange(1,6)
arr

array([1, 2, 3, 4, 5])

In [111]:
np.exp(arr)  # computes e^x for each x in arr

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [112]:
np.square(arr)

array([ 1,  4,  9, 16, 25], dtype=int32)

In [113]:
np.sqrt(np.square(arr))

array([1., 2., 3., 4., 5.])

In [114]:
np.power(arr,3)

array([  1,   8,  27,  64, 125], dtype=int32)

In [115]:
arr2 = np.arange(-3,4)
arr2

array([-3, -2, -1,  0,  1,  2,  3])

In [116]:
np.abs(arr2)

array([3, 2, 1, 0, 1, 2, 3])

In [117]:
np.fabs(arr2) 

array([3., 2., 1., 0., 1., 2., 3.])

In [126]:
np.fabs(arr2).astype(np.int32)

array([3, 2, 1, 0, 1, 2, 3])

In [124]:
np.fabs(arr2).astype(int)

array([3, 2, 1, 0, 1, 2, 3])

In [125]:
np.fabs(arr2).astype(str)

array(['3.0', '2.0', '1.0', '0.0', '1.0', '2.0', '3.0'], dtype='<U32')

In [127]:
arr2d = np.arange(1,10).reshape(3,3)
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [128]:
np.square(arr2d)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]], dtype=int32)

In [129]:
np.power(arr2d,2)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]], dtype=int32)

In [ ]:
arr2d   # is the original array modified?

In [ ]:
# ceil, floor, round to nearest integer
arr = np.exp(np.arange(1,6))
print(arr)
print(np.ceil(arr))
print(np.floor(arr))
print(np.rint(arr))

In [ ]:
# is nan
arr = np.array([1,2,4,5]) 
print(np.isnan(arr))

In [ ]:
# np.nan gives NaN
arr = np.array([1,2,np.nan,4,5])  # NaN is value used to denote not available, or null
print(np.isnan(arr))

---

#### <font color='brown'>Some binary ufuncs</font>

In [128]:
# raise elements of first array to elements of second array
arr1 = [1,2,3,4]
arr2 = [2,1,2,3]
np.power(arr1,arr2)

array([ 1,  2,  9, 64], dtype=int32)

In [129]:
powers = np.ones((3,3));
powers[0] = powers[0]*2
powers[2] = powers[2]*3
powers

array([[2., 2., 2.],
       [1., 1., 1.],
       [3., 3., 3.]])

In [130]:
powers = powers.astype(int)
powers

array([[2, 2, 2],
       [1, 1, 1],
       [3, 3, 3]])

In [131]:
arr2d = np.arange(1,10).reshape(3,3)
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [132]:
np.power(arr2d,powers)

array([[  1,   4,   9],
       [  4,   5,   6],
       [343, 512, 729]], dtype=int32)

In [133]:
# element-wise maximum
print(arr1)
print(arr2)
np.maximum(arr1,arr2)

[1, 2, 3, 4]
[2, 1, 2, 3]


array([2, 2, 3, 4])

In [134]:
arr = np.array([1,2,np.nan,4,5])
print(arr)
arr3 = [3,5,1,15,7]
print(arr3)

[ 1.  2. nan  4.  5.]
[3, 5, 1, 15, 7]


In [135]:
np.maximum(arr3,arr)

array([ 3.,  5., nan, 15.,  7.])

In [136]:
np.max(arr3,2)

AxisError: axis 2 is out of bounds for array of dimension 1

In [1]:
#From the error message 'AxisError...' it appears that he scalar argument is the "axis" or dimension number.